name: Build VS Code Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install npm dependencies
        working-directory: vs-code-extension
        run: npm ci
      - name: Package extension with vsce
        working-directory: vs-code-extension
        run: npx vsce package -o nagini-ide.vsix
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: nagini-ide
          path: 'vs-code-extension/*.vsix'
